# Generated by Django 5.2.5 on 2025-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learning_goal',
            field=models.TextField(blank=True, help_text='Comma separated learning goals', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated skills', null=True),
        ),
    ]
