# Generated by Django 5.2.5 on 2025-08-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_profile_learning_goal_alter_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('job_seeker', 'Job Seeker'), ('employee', 'Employee'), ('freelancer', 'Freelancer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50, null=True),
        ),
    ]
